#--------------------------------
#            Imports
import discord
from discord import app_commands 
import requests
from bs4 import BeautifulSoup
import python_weather
#--------------------------------

#--------------------------------
#     Discord initialisation
intents = discord.Intents.default() # What bot wants to receive
bot = discord.Client(intents=intents) # Initialises bot
tree = app_commands.CommandTree(bot) # For command calls
#--------------------------------

#--------------------------------
#       Global Variables

# Uncomment out this line if you want to specify your server
# Just allows it to be faster for updates and changes for the bot
# Replace [YOUR_SERVER_ID] with your server ID
# Also uncomment the two lines of code in the Bot Startup section
# MY_SERVER_GUILD = discord.Object(id=[YOUR_SERVER_ID]
#--------------------------------

#--------------------------------
#           Functions

# Function to parse through articles XML file
def fetch_articles(url): # url parameter referenced in the /newsround command
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'} # Fake user agent ig
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'xml') # uses bs4 to make it pretty
    return soup.find_all('item')[:5]

# Function to read that parsed data, and add it to a 2D list so that it can be used for sending messages
def read_articles(news_articles, source):
    title_array = []
    link_array = []
    summary_array = []
    news_round_array = []

    for article in news_articles:
        title = article.find('title').get_text(strip=True)

        # Cuz bbc and hachker news have different things gotta separate them
        if source == "bbc":
            summary = article.find('description').get_text(strip=True)
            link = article.find('guid').get_text(strip=True).split('#')[0]
        elif source == "hn":
            summary = f"Points: {article.find('description').get_text(strip=True).split('Points:')[1].split('<')[0].strip()}" # icl AI did this, cuz i got no clue wtf this does
            link = article.find('link').get_text(strip=True)

        title_array.append(title)
        summary_array.append(summary)
        link_array.append(link)

    # Appens all to one big list
    news_round_array.append(title_array)
    news_round_array.append(summary_array)
    news_round_array.append(link_array)
    return news_round_array

# shi to get the weather temp and description
async def _fetch_weather(city):
    async with python_weather.Client(unit=python_weather.METRIC) as client:
        weather = await client.get(city)
        return {
            "city": city,
            "temperature": weather.temperature,
            "description": weather.description,
        }
    
#--------------------------------

#--------------------------------
#            Commands

# News Round feature, currently supports hacker news & BBC News
@tree.command(name="newsround", description="Top 5 stories on BBC News World")
@app_commands.describe(source="Choose your news source")
@app_commands.choices(source=[
    app_commands.Choice(name="BBC World News", value="bbc"),
    app_commands.Choice(name="Hacker News", value="hn")
])
async def newsround(interaction: discord.Interaction, source: app_commands.Choice[str]):
    # Pick between different news sourcespip install python-weather
    if source.value == "bbc":
        url = "https://feeds.bbci.co.uk/news/world/rss.xml"
        website_name = "BBC World News"
    elif source.value == "hn":
        url = "https://hnrss.org/frontpage"
        website_name = "Hacker News Front Page"

    articles = fetch_articles(url)
    news_round_array = read_articles(articles, source.value)

    # Message
    message = f"# {interaction.user.mention} Here is your News Round!\n"
    message += f"## {website_name}:\n" # Displays which source they choose, as if they didn't already inclue a parameter (ts only for aesthetics)

    # for loop to iterate through the 2D list generated by news_round_array
    for index in range(len(news_round_array[0])):
        message += f"### {news_round_array[0][index]}\n"
        message += f"{news_round_array[1][index]}\n"
        message += f"[Read More]({news_round_array[2][index]})\n"
    await interaction.response.send_message(message, suppress_embeds = True)

# Weather feature command
@tree.command(name="weather", description="Gives the current statistics for the weather in that area")
@app_commands.describe(source="Choose the area")
@app_commands.choices(source=[
    app_commands.Choice(name="Auckland", value="akl"),
    app_commands.Choice(name="Bristol", value="brs"),
    app_commands.Choice(name="London", value="ldn"),
    app_commands.Choice(name="Los Angeles", value="la"),
    app_commands.Choice(name="New York", value="nyc"),
    app_commands.Choice(name="Tokyo", value="tky")
])
async def weather(interaction: discord.Interaction, source: app_commands.Choice[str]):
    # Different choices
    if source.value == "brs":
        city = "Bristol"
    elif source.value == "ldn":
        city = "London"
    elif source.value == "akl":
        city = "Auckland"
    elif source.value == "la":
        city = "Los Angeles"
    elif source.value == "nyc":
        city = "New York"
    elif source.value == "tky":
        city = "Tokyo"
    # just for trolling
    else:
        city = "Beijing"

    weather = await _fetch_weather(city)

    description = weather['description'].lower()

    # Ignore this big ass chunk, ts just checking the weather and adding an emoji so that it looks fancy
    # The "noqa: E701" is so that my IDE doesn't scream at me lmao
    if description == "sunny":                      emoji = "☀️"  # noqa: E701
    elif description == "clear":                    emoji = "🌙"  # noqa: E701
    elif description == "partly cloudy":            emoji = "⛅"  # noqa: E701
    elif description == "cloudy":                   emoji = "🌥️"  # noqa: E701
    elif description == "overcast":                 emoji = "☁️"  # noqa: E701
    elif description == "mist":                     emoji = "🌫️"  # noqa: E701
    elif description == "fog":                      emoji = "🌫️"  # noqa: E701
    elif description == "freezing fog":             emoji = "🌫️❄️"  # noqa: E701
    elif description == "patchy rain possible":     emoji = "🌦️"  # noqa: E701
    elif description == "patchy snow possible":     emoji = "🌨️"  # noqa: E701
    elif description == "blowing snow":             emoji = "🌨️💨"  # noqa: E701
    elif description == "blizzard":                 emoji = "❄️🌨️"  # noqa: E701
    elif description == "thundery outbreaks possible": emoji = "🌩️"  # noqa: E701
    elif description == "patchy light drizzle":     emoji = "🌦️"  # noqa: E701
    elif description == "light drizzle":            emoji = "🌧️"  # noqa: E701
    elif description == "freezing drizzle":         emoji = "🌧️❄️"  # noqa: E701
    elif description == "heavy freezing drizzle":   emoji = "🌧️❄️"  # noqa: E701
    elif description == "patchy light rain":        emoji = "🌦️"  # noqa: E701
    elif description == "light rain":               emoji = "🌧️"  # noqa: E701
    elif description == "moderate rain at times":   emoji = "🌧️"  # noqa: E701
    elif description == "moderate rain":            emoji = "🌧️"  # noqa: E701
    elif description == "heavy rain at times":      emoji = "🌧️"  # noqa: E701
    elif description == "heavy rain":               emoji = "🌧️"  # noqa: E701
    elif description == "light freezing rain":      emoji = "🌧️❄️"  # noqa: E701
    elif description == "moderate or heavy freezing rain": emoji = "🌧️❄️"  # noqa: E701
    elif description == "light sleet":              emoji = "🌨️"  # noqa: E701
    elif description == "moderate or heavy sleet":  emoji = "🌨️"  # noqa: E701
    elif description == "patchy light snow":        emoji = "🌨️"  # noqa: E701
    elif description == "light snow":               emoji = "❄️"  # noqa: E701
    elif description == "patchy moderate snow":     emoji = "🌨️"  # noqa: E701
    elif description == "moderate snow":            emoji = "❄️"  # noqa: E701
    elif description == "patchy heavy snow":        emoji = "🌨️❄️"  # noqa: E701
    elif description == "heavy snow":               emoji = "❄️❄️"  # noqa: E701
    elif description == "ice pellets":              emoji = "🧊"  # noqa: E701
    elif description == "light rain shower":        emoji = "🌦️"  # noqa: E701
    elif description == "moderate or heavy rain shower": emoji = "🌧️"  # noqa: E701
    elif description == "torrential rain shower":   emoji = "🌧️🌧️"  # noqa: E701
    elif description == "light sleet showers":      emoji = "🌨️"  # noqa: E701
    elif description == "moderate or heavy sleet showers": emoji = "🌨️"  # noqa: E701
    elif description == "light snow showers":       emoji = "🌨️"  # noqa: E701
    elif description == "moderate or heavy snow showers": emoji = "❄️"  # noqa: E701
    elif description == "light showers of ice pellets": emoji = "🧊"  # noqa: E701
    elif description == "moderate or heavy showers of ice pellets": emoji = "🧊"  # noqa: E701
    elif description == "patchy light rain with thunder": emoji = "⛈️"  # noqa: E701
    elif description == "moderate or heavy rain with thunder": emoji = "⛈️"  # noqa: E701
    elif description == "patchy light snow with thunder": emoji = "⛈️❄️"  # noqa: E701
    elif description == "moderate or heavy snow with thunder": emoji = "⛈️❄️"  # noqa: E701
    else:                                           emoji = "🌡️"  # noqa: E701

    await interaction.response.send_message(
        f"# {interaction.user.mention} Here is the weather in {city}!\n"
        f"## 🌡️{weather['temperature']}°C — {weather['description']} {emoji}"
    )

# Credits command

#--------------------------------

#--------------------------------
#          Bot startup
@bot.event 
async def on_ready():
    # tree.copy_global_to(guild=MY_SERVER_GUILD) # Read instructions under global variables
    # await tree.sync(guild=MY_SERVER_GUILD) # Read instructions under global variables
    print(f"Logged in as {bot.user}")

bot.run("[YOUR_API_KEY]") # Read README.md for instructions on this
#--------------------------------
